### PR TITLE
fixes and linked links

### PR DESCRIPTION
**Pull request by natarajansub**
fixes and linkedin links. no github links yet

### CODE REVIEW

**Comment by samitbasu** [comment]
Can you remove everything from `public`?  The `public` directory is deleted when you rebuild the site.  So put the corresponding content in the `content` dir...

**Comment by natarajansub** [comment]
> Can you remove everything from `public`? The `public` directory is deleted when you rebuild the site. So put the corresponding content in the `content` dir...

so delete the entire "public" directory?

**Comment by basusamit** [comment]
No - you can leave it.  But don't commit any changes there.

**Comment by natarajansub** [comment]
remove public folder altogether

**Comment by natarajansub** [comment]
i removed the folder zola creates it anyways

**Pull request merged**
